server:
    http:
        addr: 0.0.0.0:8080
data:
    database:
        driver: mysql
        source: root:mysql_TcKPjC@tcp(192.168.233.128:3306)/ai_server?parseTime=True&loc=Local
        reconnection_num: 5
        reconnection_time: 2s
    redis:
        addr: 192.168.233.128:6379
        username: default
        password: redis_jFFiD3
        readTimeout: 2s
        writeTimeout: 2s
log:
    ZeroLogConfig:
        Level: debug
        Pattern: development
        OutPut: logs
    LogRotate:
        Filename: service.log
        MaxSize: 1
        MaxBackups: 3
        MaxAge: 7
        Compress: true
siteInfo:
    site:
        title: Sakuras的AI小-==----
        enTitle: Sakuras's AI Site
        logo: logo
        slogan: 智能AI
        abstract: 智能AI
        beian: "1234"
    project:
        title: S=========================
        icon: icon
        webPath: /
    seo:
        keywords: "1"
        description: "2"
    register:
        isEmailRegister: false
        isWxLoginRegister: true
        isSmsRegister: true
    login:
        isUserNameLogin: true
        isEmailLogin: true
        isTelLogin: true
email:
    domain: smtp.qq.com
    port: 465
    userName: 1808479176@qq.com
    password: kvkqbbpbqrgbeeic
